apiVersion: apps/v1
kind: Deployment
metadata:
  name: device-communication
  namespace: demonstrator
  labels:
    app: device-communication
spec:
  replicas: 1
  selector:
    matchLabels:
      app: device-communication
  template:
    metadata:
      labels:
        app: device-communication
      annotations:
        prometheus.io/should_be_scraped: "true"
        prometheus.io/scrape_port: "8080"
        prometheus.io/metric_path: "/actuator/prometheus"
    spec:
      containers:
        - name: device-communication
          image: git.rss.iste.uni-stuttgart.de:5050/mosaic/demonstrator/device-communication
          resources:
            requests:
              memory: "500Mi"
              cpu: "125m"
            limits:
              memory: "2Gi"
              cpu: "0.5"
          volumeMounts:
          - mountPath: /ProtoComCalibration
            name: "protocomcalibration"
          args: ["--spring.profiles.active=kubernetes"]
          ports:
            - name: http
              containerPort: 8080
      imagePullSecrets:
        - name: gitlab-credentials
      volumes:
      - name: protocomcalibration
        persistentVolumeClaim:
          claimName: protocom-calibration
---
apiVersion: v1
kind: Service
metadata:
  name: device-communication-service
  namespace: demonstrator
  labels:
    app: device-communication-service
spec:
  type: NodePort
  selector:
    app: device-communication
  ports:
    - name: http
      protocol: TCP
      port: 3000
      targetPort: 8080