title: Kubernetes Autoscaler Comparison
description: This site will compare different autoscalers for Kubernetes
theme: just-the-docs

url: https://B3at.github.io/kubernetes-autoscaler-docs

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
